
Table app.transactions {
  id integer [increment, primary key]
  user_id integer
  account_id integer
  category_id integer
  target_account_id integer
  transaction_type transaction_type
  date timestamp [primary key]
  amount numeric
  currency varchar [default: 'HUF']
  comment varchar

  Note: "Partitioned by date and user_id"
}

Enum app.transaction_type {
  credit
  debit
  transfer
}

Table app.transaction_categories {
  id integer [increment, primary key]
  user_id integer
  category varchar [not null]
  effective_from timestamp [not null]
  effective_to timestamp
}

Table app.recurring_transactions {
  id integer [increment, primary key]
  user_id integer
  category_id integer
  recurrence recurrence
  amount numeric
  due_date_day integer
}

Enum app.recurrence {
  daily
  weekly
  monthly
  yearly
}

Table app.planned_transactions {
  id integer [increment, primary key]
  category_id integer
  user_id integer
  transaction_id integer
  transaction_status transaction_status
  amount numeric
  currency varchar [default: 'HUF']
  due_date date
  realized_date timestamp
}

Enum  app.transaction_status {
  planned
  realized
  overdue
  cancelled
}

Table app.accounts {
  id integer [increment, primary key]
  user_id integer
  account_name varchar
  account_type varchar
  currency varchar [default: 'HUF']
  effective_from date [not null]
  effective_to date
}

Table app.current_account_balance {
  id integer [increment, primary key]
  user_id integer
  account_id integer
  balance numeric
  currency varchar [default: 'HUF']
  last_modified_date date
}

Table app.balance_history {
  id integer [increment, primary key]
  user_id integer
  account_id integer
  balance numeric
  currency varchar [default: 'HUF']
  month date
  created_at date
}

Table app.users {
  id integer [increment, primary key]
  first_name varchar
  last_name varchar
}

Table app.exchange_rates {
  id integer [increment, primary key]
  from_currency varchar
  to_currency varchar
  rate numeric
  date date
}

Table app.closed_months {
  id integer [increment, primary key]
  user_id integer
  month integer
  year integer
}

Table app.date_dim {
  date_id integer [primary key]
  date date
  year integer
  month integer
  week integer
  day integer
  is_weekend bool
  is_holiday bool
}